spring: 
  profiles:
    active:
    - dev

---

servce:
  port: 8201 
  
spring:
  profiles: dev      #开发环境
  application:
    name:  microservicecloud-config-client
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
  
---

servce:
  port: 8202 
  
spring:
  profiles: test      #测试环境
  application:
    name:  microservicecloud-config-client
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
      
      
      
      
      